// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function toString(squareType) {
  return squareType;
}

function App$Square(props) {
  return React.createElement("button", {
              className: "square"
            });
}

var Square = {
  toString: toString,
  make: App$Square
};

function App$Board(props) {
  return React.createElement("div", undefined, React.createElement("div", {
                  className: "board-row"
                }, React.createElement(App$Square, {}), React.createElement(App$Square, {}), React.createElement(App$Square, {})), React.createElement("div", {
                  className: "board-row"
                }, React.createElement(App$Square, {}), React.createElement(App$Square, {}), React.createElement(App$Square, {})), React.createElement("div", {
                  className: "board-row"
                }, React.createElement(App$Square, {}), React.createElement(App$Square, {}), React.createElement(App$Square, {})));
}

var Board = {
  make: App$Board
};

function App$default(props) {
  return React.createElement("div", undefined);
}

var $$default = App$default;

export {
  Square ,
  Board ,
  $$default as default,
}
/* react Not a pure module */
