// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function toString(squareType) {
  return squareType;
}

function App$Field(props) {
  var _type = props._type;
  if (_type === "square") {
    return React.createElement("button", {
                className: _type
              }, "X");
  } else {
    return React.createElement("button", {
                className: _type
              }, "O");
  }
}

var Field = {
  toString: toString,
  make: App$Field
};

function App$default(props) {
  return React.createElement(App$Field, {
              _type: "square"
            });
}

var $$default = App$default;

export {
  Field ,
  $$default as default,
}
/* react Not a pure module */
